services:

  kafka:
    image: apache/kafka-native:3.8.@sha256:8c671522f7f84d0fd20b1482a1d41fa4544eff02b4027673116d4fa74a508106
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://kafka:9093,HOST://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,HOST://127.0.0.1:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 4
    ports:
      - "9094:9094"
    healthcheck:
      test: nc -z kafka:9092
      interval: 10s
      retries: 30
      start_period: 10s
      timeout: 10s

  producer:
    build: endpoints
    command: producer
    container_name: producer
    healthcheck:
      test: ok
      interval: 2s
      retries: 30
      start_period: 2s
      timeout: 5s
    depends_on:
      kafka:
        condition: service_healthy
    healthcheck:
      test: ok
      interval: 10s
      start_period: 10s
      timeout: 10s

  consumer:
    build: endpoints
    command: consumer
    container_name: consumer
    healthcheck:
      test: ok
      interval: 2s
      retries: 30
      start_period: 2s
      timeout: 5s
    depends_on:
      kafka:
        condition: service_healthy

  jobmanager:
    build: processors
    ports:
      - "8081:8081"
    command: standalone-job --job-classname w08r_flink.processor --jars /cp/processor-0.0.0-standalone.jar
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        jobmanager.memory.process.size: 768m
        parallelism.default: 4
    depends_on:
      producer:
        condition: service_healthy
    volumes:
      - ./urls.csv:/urls.csv:rw
      - ./checkpoints:/checkpoints:rw

  taskmanager:
    build: processors
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 4
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 1
        taskmanager.memory.process.size: 1g
        parallelism.default: 1
    volumes:
      - ./urls.csv:/urls.csv:rw
      - ./checkpoints:/checkpoints:rw
